#! /usr/bin/env python
'''
Function:
	Provide 1 commands: 
		cpnot: cp a directory except some files

Usage, examples:
	cpnot -not "a b c" X Y
'''


operate = 'rm'


import sys
import os

def ShellCmd( cmd ) : 
	strlist = os.popen(cmd).readlines()
	for i in xrange(len(strlist)): strlist[i] = strlist[i][:-1]
	return strlist

a = sys.argv[1:]
b = a[1+a.index('-not')]
a.remove('-not')
a.remove(b)
try : a.remove('-r')
except : pass

b = b.split(' ')
while ('' in b) : b.remove('')

try : a[0] = os.path.abspath(os.path.expanduser(a[0]))
except : raise Exception('Missing startdir and targetdir')
try : a[1] = os.path.abspath(os.path.expanduser(a[1]))
except : raise Exception('Missing targetdir')
if (not os.path.exists(a[1])) : os.mkdir(a[1])

for i in xrange(len(b)) : 
	b[i] = os.path.abspath(os.path.expanduser(b[i]))

exclude = []
for i in xrange(len(b)) : exclude += ShellCmd('find '+b[i])

files = ShellCmd('find '+a[0])
files.remove(a[0])
for i in xrange(len(exclude)) : files.remove(exclude[i])

rest = ''
for i in xrange(len(files)) : 
	start = files[i]
	if (start.split('/')[-1] in excludeall) : continue
	target = a[1] + start[len(a[0]):]
	if (os.path.isdir(start)) : 
		if (not os.path.exists(target)) : os.mkdir(target)
#	else : 
#		cmd = 'cp '+start+' '+target
#		os.system(cmd)
	else : rest += start+' '
if (rest != '') : os.system('cp '+rest+a[1])
