#! /usr/bin/env python
'''
Function:
	Provide 1 commands: 
		cpnot: rm a directory except some files

Usage, examples:
	rmnot -not "a b c" X
		Input "YeS" to remove, other to stop
	rmnot -not "a b c" X YeS
		Use last argument "YeS" as input
'''


operate = 'rm'


import sys
import os

def ShellCmd( cmd ) : 
	strlist = os.popen(cmd).readlines()
	for i in xrange(len(strlist)): strlist[i] = strlist[i][:-1]
	return strlist

a = sys.argv[1:]
b = a[1+a.index('-not')]
a.remove('-not')
a.remove(b)
try : a.remove('-r')
except : pass

try : a[0] = os.path.abspath(os.path.expanduser(a[0]))
except : raise Exception('Missing targetdir')

if (len(a) == 1) : whichargv = 'usesysargvtogetwhich'
else : whichargv = a[1]
a = a[0]

b = b.split(' ')
while ('' in b) : b.remove('')

for i in xrange(len(b)) : 
	b[i] = os.path.abspath(os.path.expanduser(a+'/'+b[i]))

exclude = []
for i in xrange(len(b)) : exclude += ShellCmd('find '+b[i])

files = ShellCmd('find '+a)
files.remove(a)
for i in xrange(len(exclude)) : files.remove(exclude[i])
for i in xrange(len(exclude)) : 
	n = 0
	for j in xrange(len(files)) : 
		if (exclude[i][:len(files[j-n])] == files[j-n]) : 
			files.pop(j-n)
			n += 1

if (whichargv == 'usesysargvtogetwhich') : 
	N = len(str(len(files)))
	print '\n----------------------------------------------'
	for i in xrange(len(files)) : 
		idx = (('%'+str(N)+'i') % i)
		print idx+'-  '+files[i]
	print '\n----------------------------------------------'
	print 'Do you really want to delete all files above ?'
	print 'Press "YeS" to YES, others to NO\n'
	which = raw_input()
else : which = whichargv

if (which != 'YeS') : 
	print 'Cancel !'
	exit()

for i in xrange(len(files)) : 
	start = files[i]
	target = a + start[len(a):]
	if (os.path.exists(target)) : 
		os.system('rm -rf '+target)
		print target

