#! /usr/bin/env python
import sys
import os

if (len(sys.argv) == 1) : 
	print 'Error: socks5 on/off'
	exit()
else : status = sys.argv[1].lower()

cmd = 'sudo networksetup -setsocksfirewallproxystate Ethernet '+status
os.system(cmd)
cmd = 'sudo networksetup -setsocksfirewallproxystate Wi-Fi '+status
os.system(cmd)

