#! /usr/bin/env python
# jizhi on 20160729
import os
import sys
import time


if (len(sys.argv) > 1) : 
	if (sys.argv[1] == 'init') : 
		print 'git config --global user.name : Input your git name'
		username = raw_input()  # jizhi
		print 'git config --global user.email : Input your git e-mail'
		useremail = raw_input()
		if ('' in [username, useremail]) : raise Exception('user.name="'+username+'", user.email='+useremail)
		os.system('git init')
		os.system('git config --global user.name "'+username+'"')
		os.system('git config --global user.email '+useremail)


def Backup() : 
	bktime=time.strftime('%Y.%m.%d.%p.%I.%M.%S', time.localtime())
	pwd = os.popen('pwd').readlines()[0][:-1].split('/')[-1]
	os.system('rm -r ~/.'+pwd+'*')
	pwd = '~/.'+pwd+'_'+bktime+'/'
	print '\nBackup to '+pwd+'\n'
	os.system('mkdir '+pwd)
	os.system('cp -r * '+pwd)
	os.system('cp ~/jizhi.py .')


def ShellCmd( cmd ) : 
	strlist = os.popen(cmd).readlines()
	for i in xrange(len(strlist)): strlist[i] = strlist[i][:-1]
	return strlist


# deleted
delete = []
status = os.popen('git status').readlines()
for i in xrange(len(status)) :
	if (status[i][1:9] == 'deleted:') : 
		delete = status[i][9:].split(' ')[-1][:-1]
		os.system('git rm '+delete)
	

os.system('git status')
print '-------------------------------------------------------\n'
print 'Do you really want to add and commit all of these?'
print 'Press Y to yes, others to no.'
a = raw_input()


if (a.lower() in ['y', 'yes']) : 
	Backup()
	os.system('git add .')
	mdtime=time.strftime('%Y/%m/%d %p %I:%M:%S', time.localtime())
	os.system('git commit -m "Updated at '+mdtime+'"')
	os.system('git push -u origin master')
else : print 'Cancel'


