#! /usr/bin/env python
# jizhi on 20160822
import os
import sys
import time



notlist = '.DS_Store .git/'
notgitlab = ''
if (len(sys.argv) > 1) : 
	notgitlab = sys.argv[-1]

	if (sys.argv[1] == 'init') : 
		print 'git config --global user.name : Input your git name'
		username = raw_input()  # jizhi
		print 'git config --global user.email : Input your git e-mail'  # bao.ac.cn
		useremail = raw_input()
		if ('' in [username, useremail]) : raise Exception('user.name="'+username+'", user.email='+useremail)
		os.system('git init')
		os.system('git config --global user.name "'+username+'"')
		os.system('git config --global user.email '+useremail)

	elif (sys.argv[1] == '-not') : 
		for i in xrange(len(sys.argv[2:])) : 
			notlist += ' '+sys.argv[2+i]
notlist = '"'+notlist+'"'


def Backup( nostlist ) : 
	pwd = os.popen('pwd').readlines()[0][:-1].split('/')[-1]
	if ('_github' == pwd[-7:]) : pwd = pwd[:-7]+'_gitlab'
	pwd = '~/.'+pwd+'/'
	pwdabs = os.path.abspath(os.path.expanduser(pwd))
	if (not os.path.exists(pwdabs)) : os.mkdir(pwdabs)
	if (not os.path.exists(pwdabs+'/.git')) : raise Exception('Please "git init '+pwd+'"')
	print '\nBackup to  '+pwd+'\n'
	# remove all except .git
	os.system('rmnot -not ".git" '+pwdabs+' YeS')
	os.system('cpnot -not '+notlist+' . '+pwdabs)
	return pwdabs



def ShellCmd( cmd ) : 
	strlist = os.popen(cmd).readlines()
	for i in xrange(len(strlist)): strlist[i] = strlist[i][:-1]
	return strlist


# deleted
delete = []
status = os.popen('git status').readlines()
for i in xrange(len(status)) :
	if (status[i][1:9] == 'deleted:') : 
		delete = status[i][9:].split(' ')[-1][:-1]
		os.system('git rm '+delete)
	

os.system('git status')
print '-------------------------------------------------------\n'
print 'Do you really want to add and commit all of these?'
print 'Press Y to YES, others to NO'
a = raw_input()


if (a.lower() in ['y', 'yes']) : 
	if (notgitlab != 'notgitlab') : backuppath = Backup(notlist)
	os.system('git add .')
	mdtime=time.strftime('%Y/%m/%d %p %I:%M:%S', time.localtime())
	os.system('git commit -m "Updated at '+mdtime+'"')
	os.system('git push -u origin master')
	if (notgitlab != 'notgitlab') :  # also update to gitlab
		os.system(backuppath+'/gitupdate notgitlab')
else : print 'Cancel !'


