#! /usr/bin/env python
# jizhi on 20160822
'''
(1) gitupdate init
(2) gitupdate -not "Foreground/ Tool/"
(3) gitupdate
'''


import os
import sys
import time


notlist = ['*.DS_Store .git/']
if (len(sys.argv) > 1) : 

	if (sys.argv[1] == 'init') : 
		print 'git config --global user.name : Input your git name'
		username = raw_input()  # jizhi
		print 'git config --global user.email : Input your git e-mail'  # bao.ac.cn
		useremail = raw_input()
		if ('' in [username, useremail]) : raise Exception('user.name="'+username+'", user.email='+useremail)
		os.system('git init')
		os.system('git config --global user.name "'+username+'"')
		os.system('git config --global user.email '+useremail)

	elif (sys.argv[1] == '-not') : 
		for i in xrange(len(sys.argv[2:])) : 
			notlist += ' '+sys.argv[2+i]
	if (notlist[0] == ' ') : notlist = notlist[1:]
notlist = '"'+notlist+'"'



def Backup( nostlist ) : 
	pwd = os.popen('pwd').readlines()[0][:-1].split('/')[-1]
#	bktime=time.strftime('%Y.%m.%d.%p.%I.%M.%S', time.localtime())
	pwd = '~/.'+pwd+'_backup/'
	pwdabs = os.path.abspath(os.path.expanduser(pwd))
	if (os.path.exists(pwdabs)) : os.system('rm -rf '+pwdabs)
	os.mkdir(pwdabs)
	print '\nBackup to  '+pwd+'\n'
	os.system('cpnot -v -not '+notlist+' . '+pwdabs)
#	aa = ShellCmd('cpnot -not '+notlist+' . '+pwdabs)
	exit()
	print aa
#	print exclude, files
	exit()
	return pwdabs



def ShellCmd( cmd ) : 
	strlist = os.popen(cmd).readlines()
	for i in xrange(len(strlist)): strlist[i] = strlist[i][:-1]
	return strlist


# deleted
delete = []
status = os.popen('git status').readlines()
for i in xrange(len(status)) :
	if (status[i][1:9] == 'deleted:') : 
		delete = status[i][9:].split(' ')[-1][:-1]
		os.system('git rm '+delete)


Backup(notlist)
exit()
	

os.system('git status')
print '-------------------------------------------------------\n'
print 'Do you really want to add and commit all of these?'
print 'Press Y to YES, others to NO'
a = raw_input()


if (a.lower() in ['y', 'yes']) : 
	backuppath = Backup(notlist)
	exit()
	os.system('git add .')
	mdtime=time.strftime('%Y/%m/%d %p %I:%M:%S', time.localtime())
	os.system('git commit -m "Updated at '+mdtime+'"')
	os.system('git push -u origin master')
else : print 'Cancel !'


